
DBM_AllSavedOptions = {
["Default"] = {
["DontShowFarWarnings"] = true,
["AlwaysPlayVoice"] = false,
["SpamSpecRolestack"] = false,
["DontRestoreIcons"] = false,
["NPIconYOffset"] = 0,
["SpecialWarningFlash5"] = true,
["NPIconTextMaxLen"] = 7,
["SpecialWarningFlash1"] = true,
["DontPlayTrivialSpecialWarningSound"] = true,
["SWarnNameInNote"] = true,
["SpecialWarningSound2"] = 543587,
["InfoFramePoint"] = "CENTER",
["EventSoundMusicCombined"] = false,
["WorldBossAlert"] = false,
["SpamSpecInformationalOnly"] = false,
["WorldBuffAlert"] = false,
["SpamSpecRoledispel"] = false,
["DisableMusic"] = false,
["ShowGuildMessages"] = true,
["ShowAllVersions"] = true,
["SpecialWarningSound3"] = "Interface\\AddOns\\DBM-Core\\sounds\\AirHorn.ogg",
["SpamSpecRolesoak"] = false,
["ShowWarningsInChat"] = true,
["InfoFrameFontStyle"] = "None",
["WarningFontStyle"] = "None",
["VPReplacesSA1"] = true,
["ChatFrame"] = "DEFAULT_CHAT_FRAME",
["CastNPIconGlowBehavior"] = 1,
["RangeFrameRadarX"] = 100,
["LogCurrentRaids"] = true,
["InfoFrameCols"] = 0,
["NPIconTimerEnabled"] = true,
["LatencyThreshold"] = 250,
["ShowGuildMessagesPlus"] = false,
["LFDEnhance"] = true,
["LogCurrentMythicRaids"] = true,
["DontPlayPrivateAuraSound"] = false,
["HideBossEmoteFrame2"] = true,
["DisableChatBubbles"] = false,
["HideObjectivesFrame"] = true,
["SpecialWarningShortText"] = true,
["DontShowPTText"] = false,
["FilterBInterruptHealer"] = true,
["SpecialWarningFontSize2"] = 35,
["SpecialWarningFlashCol5"] = {
0.2,
1,
1,
},
["NewsMessageShown2"] = 2,
["NPIconTextFont"] = "standardFont",
["EventSoundPullTimer"] = "None",
["NPIconTimerFontStyle"] = "None",
["SpecialWarningVibrate2"] = false,
["SpecialWarningFlashCount2"] = 1,
["NPAuraText"] = true,
["EventSoundDungeonBGM"] = "None",
["AutoAcceptGuildInvite"] = false,
["VPReplacesCustom"] = false,
["VPReplacesSA4"] = true,
["SpecialWarningFlashDura3"] = 1,
["WarningShortText"] = true,
["SpecialWarningFlash4"] = true,
["DisableSFX"] = false,
["SpecialWarningFlashDura4"] = 0.7,
["SpecialWarningFlashCol3"] = {
1,
0,
0,
},
["ModelSoundValue"] = "Short",
["SpecialWarningY"] = 75,
["VPReplacesSA2"] = true,
["ReplaceMyConfigOnOverride"] = false,
["LogTrivialDungeons"] = false,
["RaidWarningSound"] = 566558,
["CustomSounds"] = 0,
["RoleSpecAlert"] = true,
["LogCurrentMPlus"] = true,
["DontPlayPTCountdown"] = false,
["HideMovieInstanceAnywhere"] = true,
["WarningIconLeft"] = true,
["RangeFrameLocked"] = false,
["DontDoSpecialWarningVibrate"] = false,
["SpamSpecRolegtfo"] = false,
["SpecialWarningFlashDura2"] = 0.4,
["LogTrivialRaids"] = false,
["FilterVoidFormSay2"] = true,
["GroupOptionsExcludeIcon"] = false,
["FilterBTargetFocus"] = true,
["RecordOnlyBosses"] = false,
["ShowBerserkWarnings"] = true,
["DontPlayCountdowns"] = false,
["OverrideBossIcon"] = false,
["SpecialWarningFlashAlph1"] = 0.3,
["ShowDefeatMessage"] = true,
["FilterCrowdControl"] = true,
["InfoFrameShowSelf"] = false,
["WarningFontShadow"] = true,
["DontShowBossTimers"] = false,
["SpecialWarningFontStyle"] = "THICKOUTLINE",
["InfoFrameLines"] = 0,
["WarningIconChat"] = true,
["HideGuildChallengeUpdates"] = true,
["ShowPizzaMessage"] = true,
["RangeFrameSound2"] = "none",
["HideTooltips"] = false,
["LogCurrentMythicZero"] = false,
["GUIWidth"] = 800,
["NPIconTextFontSize"] = 10,
["EventSoundMusic"] = "None",
["LogTWRaids"] = false,
["NoTimerOverridee"] = true,
["HelpMessageVersion"] = 3,
["SpecialWarningFlashAlph2"] = 0.3,
["DontShowHudMap2"] = false,
["SpecialWarningFlashCount4"] = 2,
["ShowSWarningsInChat"] = true,
["HideMovieDuringFight"] = true,
["RangeFrameRadarY"] = -100,
["OverrideBossAnnounce"] = false,
["CoreSavedRevision"] = 20240911080538,
["RangeFrameX"] = 50,
["NPIconGrowthDirection"] = "CENTER",
["RangeFrameY"] = -50,
["SpecialWarningFlashAlph3"] = 0.4,
["FilterTInterruptHealer"] = true,
["FakeBWVersion"] = false,
["NPIconXOffset"] = 0,
["SpecialWarningFlashCol2"] = {
1,
0.5,
0,
},
["WarningAlphabetical"] = true,
["SpecialWarningPoint"] = "CENTER",
["FilterBInterruptCooldown"] = true,
["CheckGear"] = true,
["NPIconTextEnabled"] = true,
["SpecialWarningX"] = 0,
["DontShowPT2"] = false,
["MoviesSeen"] = {
},
["ShowQueuePop"] = true,
["SpecialWarningFlashCol4"] = {
1,
0,
1,
},
["DebugMode"] = false,
["DisableGuildStatus"] = false,
["ShowReminders"] = true,
["ChosenVoicePack2"] = "None",
["NPIconTimerFont"] = "standardFont",
["AFKHealthWarning2"] = false,
["SpecialWarningVibrate1"] = false,
["EventSoundEngage2"] = "None",
["InfoFrameY"] = -75,
["SpecialWarningSound"] = 569200,
["WarningIconRight"] = true,
["UseSoundChannel"] = "Master",
["ShowRespawn"] = true,
["HideMovieNonInstanceAnywhere"] = false,
["DontAutoGossip"] = false,
["VPReplacesSA3"] = true,
["AlwaysShowSpeedKillTimer2"] = false,
["SpecialWarningFlashCount5"] = 3,
["DebugLevel"] = 1,
["VPReplacesGTFO"] = true,
["BadTimerAlert"] = false,
["DontShowPTNoID"] = false,
["HideGarrisonToasts"] = true,
["RangeFramePoint"] = "CENTER",
["SpecialWarningFontShadow"] = false,
["NPIconTimerFontSize"] = 18,
["SpecialWarningFlashCol1"] = {
1,
1,
0,
},
["DontShowNameplateIconsCD"] = false,
["SWarnClassColor"] = true,
["UseNameplateHandoff"] = true,
["DontShowNameplateIconsCast"] = false,
["SpecialWarningFlashAlph4"] = 0.4,
["PTCountThreshold2"] = 5,
["VPReplacesAnnounce"] = true,
["oRA3AnnounceConsumables"] = false,
["CountdownVoice2"] = "Kolt",
["NPIconAnchorPoint"] = "TOP",
["ArrowPosX"] = 0,
["AITimer"] = true,
["LogTWDungeons"] = false,
["NPIconSize"] = 30,
["DontShowTrashTimers"] = false,
["AutologBosses"] = false,
["LogCurrentHeroic"] = false,
["VPDontMuteSounds"] = false,
["WarningColors"] = {
{
["b"] = 0.9411765336990356,
["g"] = 0.8000000715255737,
["r"] = 0.4117647409439087,
},
{
["b"] = 0,
["g"] = 0.9490196704864502,
["r"] = 0.9490196704864502,
},
{
["b"] = 0,
["g"] = 0.501960813999176,
["r"] = 1,
},
{
["b"] = 0.1019607931375504,
["g"] = 0.1019607931375504,
["r"] = 1,
},
},
["SWarningAlphabetical"] = true,
["BlockNoteShare"] = false,
["DontPlaySpecialWarningSound"] = false,
["NPIconGlowBehavior"] = 1,
["OverrideBossTimer"] = false,
["OverrideBossSay"] = false,
["FilterTInterruptCooldown"] = true,
["RangeFrameRadarPoint"] = "CENTER",
["DontShowInfoFrame"] = false,
["FilterDispel"] = true,
["FilterTrashWarnings2"] = true,
["RLReadyCheckSound"] = true,
["SpecialWarningFlashDura5"] = 1,
["DisableAmbiance"] = false,
["GUIHeight"] = 600,
["DontRestoreRange"] = false,
["ShowWAKeys"] = true,
["SpecialWarningFlashCount3"] = 3,
["RangeFrameUpdates"] = "Average",
["WhisperStats"] = false,
["SilentMode"] = false,
["InfoFrameFontSize"] = 12,
["WarningDuration2"] = 1.5,
["SpecialWarningFlashAlph5"] = 0.5,
["SpecialWarningDuration2"] = 1.5,
["WarningPoint"] = "CENTER",
["SpecialWarningVibrate4"] = true,
["ShowEngageMessage"] = true,
["RangeFrameSound1"] = "none",
["EventSoundWipe"] = "None",
["FilterTTargetFocus"] = true,
["EventSoundVictory2"] = "Interface\\AddOns\\DBM-Core\\sounds\\Victory\\SmoothMcGroove_Fanfare.ogg",
["AutoExpandSpellGroups"] = false,
["LastRevision"] = 0,
["GUIPoint"] = "TOP",
["SettingsMessageShown"] = true,
["EventMusicMythicFilter"] = true,
["SpecialWarningFlashDura1"] = 0.3,
["AdvancedAutologBosses"] = false,
["SpecialWarningSound4"] = 552035,
["DontSetIcons"] = false,
["SpamSpecRoletaunt"] = false,
["SpamSpecRoleswitch"] = false,
["CountdownVoice"] = "Corsica",
["DontShowUserTimers"] = false,
["SpamSpecRoledefensive"] = false,
["CountdownVoice3"] = "Smooth",
["DontShowSpecialWarningText"] = false,
["EventDungMusicMythicFilter"] = true,
["DisableStatusWhisper"] = false,
["NPIconSpacing"] = 0,
["GUIY"] = -27.43366050720215,
["RangeFrameFrames"] = "radar",
["SpecialWarningVibrate5"] = true,
["CastNPIconGlowType"] = 2,
["SpecialWarningIcon"] = true,
["InfoFrameFont"] = "standardFont",
["NoAnnounceOverride"] = true,
["SpecialWarningFontCol"] = {
1,
0.7,
0,
},
["FilterTankSpec"] = true,
["WorldBossNearAlert"] = false,
["WarningFont"] = "standardFont",
["WarningX"] = 0,
["EnableModels"] = true,
["WarningFontSize"] = 20,
["SpecialWarningFont"] = "standardFont",
["ArrowPosY"] = -150,
["ArrowPoint"] = "TOP",
["DontShowSpecialWarningFlash"] = false,
["DontShowBossAnnounces"] = false,
["SpecialWarningVibrate3"] = true,
["DontSendBossGUIDs"] = false,
["DontShowTargetAnnouncements"] = true,
["FilterInterruptNoteName"] = true,
["DebugSound"] = true,
["AutoAcceptFriendInvite"] = false,
["AutoRespond"] = true,
["SpecialWarningFlashCount1"] = 1,
["PullVoice"] = "Corsica",
["SpecialWarningSound5"] = 554236,
["DontSendYells"] = true,
["SpamSpecRoleinterrupt"] = false,
["SpecialWarningFlash2"] = true,
["NPIconTextFontStyle"] = "None",
["SpecialWarningFlash3"] = true,
["DontShowEventTimers"] = false,
["Enabled"] = true,
["AutoReplySound"] = true,
["ShortTimerText"] = true,
["DisableRaidIcons"] = false,
["EnableWBSharing"] = true,
["WarningY"] = 260,
["DoNotLogLFG"] = true,
["HideMovieOnlyAfterSeen"] = true,
["StripServerName"] = true,
["DontShowRangeFrame"] = true,
["GUIX"] = -310.619140625,
["InfoFrameX"] = 75,
["GroupOptionsExcludePA"] = false,
["CDNPIconGlowType"] = 1,
["SendDungeonBossGUIDs"] = true,
["DontShowNameplateIcons"] = false,
},
}
DBM_MinimapIcon = {
["minimapPos"] = 152.6043441601308,
["showInCompartment"] = true,
}
DBM_AnnoyingPopupDisables = {
["Dungeons"] = 1725463541,
}
DBM_ModsToLoadWithFullTestSupport = {
["addonsWithTests"] = {
},
["bossModsWithTests"] = {
},
}
