
Details_StreamerDB = {
["characters"] = {
["Tempos - Tichondrius"] = "Pazuru - Tichondrius",
["Jiesuo - 金色平原"] = "Pazuru - Tichondrius",
["Aqei - Tichondrius"] = "Pazuru - Tichondrius",
["Rare - 萨格拉斯"] = "Pazuru - Tichondrius",
["Moradin - Tichondrius"] = "Pazuru - Tichondrius",
["Beppan - Tichondrius"] = "Pazuru - Tichondrius",
["Lolth - 国王之谷"] = "Pazuru - Tichondrius",
["Rage - 金色平原"] = "Pazuru - Tichondrius",
["Asima - Tichondrius"] = "Pazuru - Tichondrius",
["Pazuru - Tichondrius"] = "Pazuru - Tichondrius",
["Voodo - Tichondrius"] = "Pazuru - Tichondrius",
["福音 - 萨格拉斯"] = "Pazuru - Tichondrius",
["Zehir - Tichondrius"] = "Pazuru - Tichondrius",
["Zxcvb - 国王之谷"] = "Pazuru - Tichondrius",
["Voodoo - 萨格拉斯"] = "Pazuru - Tichondrius",
},
["profiles"] = {
["Pazuru - Tichondrius"] = {
["use_square_mode"] = false,
["is_first_run"] = false,
["arrow_color"] = {
1,
1,
1,
0.5,
},
["scale"] = 1,
["main_frame_size"] = {
300.0000610351563,
500.0000305175781,
},
["minimap"] = {
["minimapPos"] = 157.9098286737122,
["radius"] = 160,
["hide"] = false,
},
["point"] = "CENTER",
["arrow_anchor_x"] = 0,
["y"] = 0,
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["font_color"] = {
1,
1,
1,
1,
},
["row_height"] = 20,
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["use_spark"] = true,
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["main_frame_strata"] = "LOW",
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = 0,
["x"] = -0.00042724609375,
["update_speed"] = 0.05,
["size"] = 32,
["attribute_type"] = 1,
},
["x"] = -0.00030517578125,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["arrow_anchor_y"] = 0,
["font_size"] = 10,
["main_frame_locked"] = false,
["author"] = "Terciob",
},
},
}
