
Details_StreamerDB = {
["characters"] = {
["Hijiwar - Tichondrius"] = "Lolthis - Tichondrius",
["Amitabha - Tichondrius"] = "Lolthis - Tichondrius",
["Yesrpg - Tichondrius"] = "Lolthis - Tichondrius",
["Sigurd - Tichondrius"] = "Lolthis - Tichondrius",
["Lolthis - Tichondrius"] = "Lolthis - Tichondrius",
["Tempos - Tichondrius"] = "Lolthis - Tichondrius",
["Beppan - Tichondrius"] = "Lolthis - Tichondrius",
["Moradin - Tichondrius"] = "Lolthis - Tichondrius",
},
["profiles"] = {
["Lolthis - Tichondrius"] = {
["use_square_mode"] = false,
["is_first_run"] = false,
["arrow_color"] = {
1,
1,
1,
0.5,
},
["scale"] = 1,
["main_frame_size"] = {
299.9998168945313,
500.0000305175781,
},
["minimap"] = {
["minimapPos"] = 160,
["radius"] = 160,
["hide"] = false,
},
["row_height"] = 20,
["arrow_anchor_x"] = 0,
["font_color"] = {
1,
1,
1,
1,
},
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["point"] = "CENTER",
["main_frame_strata"] = "LOW",
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["use_spark"] = true,
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["author"] = "Terciob",
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["font_size"] = 10,
["y"] = -6.103515625e-05,
["x"] = 0.000213623046875,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = -9.1552734375e-05,
["x"] = 0.000244140625,
["size"] = 32,
["update_speed"] = 0.05,
["attribute_type"] = 1,
},
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["main_frame_locked"] = false,
["arrow_anchor_y"] = 0,
},
},
}
